name: .NET 6 Chapter 22
on:
  push:
    branches:
    - main
env:
  DOTNET_CORE_VERSION: 6.0.x
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          include-prerelease: True
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
      - name: Install dependencies
        run: dotnet restore ./ch22
      - name: Build
        run: dotnet build ./ch22 --configuration Release --no-restore
      - name: Test
        run: dotnet test ./ch22 --no-restore --verbosity normal
